### ISSUE TITLE
Is Color mode for 1660 Super really not supported?

### ISSUE THREAD

**Issue by wasi-master** [dynamiquel/NVIDIA-Ansel-AI-Enhancer#9]
> NVIDIA Turing (20 series) or newer display adapter (for colour support)

The 1660 Super is based on NVIDIA Turing microarchitecture [[1](https://en.wikipedia.org/wiki/Turing_(microarchitecture)#Products_using_Turing)] but it's not newer than 20 series, so what exactly is required? Tensor cores? The NVIDIA Ansel supported gpu list does mention 1660 super [[2](https://www.nvidia.com/en-us/geforce/technologies/ansel/supported-gpus/)] and the product page for 1660 Super mentions Ansel as a feature [[3](https://www.nvidia.com/en-us/geforce/graphics-cards/gtx-1660-super/)]

Can someone clarify why the 1660 Super isn't supported?

**Comment by dynamiquel** [comment]
If you believe the 1660 Super is supported, then you should be able to enable 'Force Mode'. This disables all GPU-related checks.

Tensor cores are required for the colour mode to work. To my knowledge, the non-RTX cards do not contain Tensor cores.

This app basically requires the same requirements as the [Nvidia Broadcast](https://www.nvidia.com/en-gb/geforce/broadcasting/broadcast-app/) app does, as that too uses Tensor cores.
_I have heard that there's a workaround to force Nvidia Broadcast to use CUDA cores instead of Tensor cores (it just's not as efficient). Perhaps a similar solution could also work with Ansel AI._

**Ansel** and **Ansel AI** are two different things. Ansel is simply a type of photo mode and advanced screenshotting software. Ansel AI is an algorithm that is often used with Ansel to make the image look better.

**Comment by wasi-master** [comment]
Oh, thanks for the clarification, I'll try the Force Mode

**Comment by wasi-master** [comment]
So I tried it and it outputs a black image. So I guess color isn't supported on my card. Ah well
